# frozen_string_literal: true

require 'rake/testtask'
require_relative 'src/application'

task default: :test

desc 'Run File Cleaner'
Rake::Task.define_task(:run_file_cleaner) do
  puts 'Provide the directory which contains files you would like to delete'
  dirname = $stdin.gets&.chomp&.strip

  puts 'Provide the dirname or filename pattern you would like to delete'
  pattern = $stdin.gets&.chomp&.strip

  puts 'Provide d(dry_run: default) to make sure what directories and files are to be delete first. Then, provide e(execution) if you would truly like to delete the files. This operation is cannot be undone, so be alert to your operation!'
  mode = $stdin.gets&.chomp&.strip

  params = { dirname:, pattern:, mode: }.reject { |_, value| value&.empty? }

  Application.run(**params)
end

desc 'Run all tests'
Rake::TestTask.new do |task|
  task.pattern = File.join('.', '**', '*_test.rb')
end
